### ISSUE TITLE
EC082_G1_230406_C.raw

### ISSUE THREAD

**Issue by sorenwacker** [LewisResearchGroup/lrg-omics#72]
![image](https://user-images.githubusercontent.com/3391614/231307501-397d5168-4e96-4eb5-8993-8f659051c55f.png)

There are several problems with the QC extraction

This works:
![image](https://user-images.githubusercontent.com/3391614/231307644-abffcab3-b066-49c5-b7ee-898d114f4c99.png)

This does not:
![image](https://user-images.githubusercontent.com/3391614/231307695-4d23e299-b939-44b1-8855-11aec9e9ee62.png)

It looks like `maxquant_qc_evidence()` expects at least two lines of the same QC peptide for some reason.

It crashes with:
```
  File "/mnt/c/Users/soere/workspace/lrg-omics/lrg_omics/proteomics/maxquant/quality_control.py", line 378, in maxquant_qc_evidence
    f"reporter_intensity_corrected_qc{pept_list.index(i) + 1}_ave": float(
  File "/home/swacker/miniconda3/envs/lrg/lib/python3.10/site-packages/pandas/core/series.py", line 206, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'float'>
```

**Comment by sorenwacker** [comment]
This seems to be the reason why some samples are not showing up in the QC pipeline.

This pattern is unreliable:

                f"reporter_intensity_corrected_qc{pept_list.index(i) + 1}_ave": float(
                    df_pept.filter(regex="Reporter intensity corrected").mean(axis=1)
                ),

**Comment by sorenwacker** [comment]
We need a type check for `pept_list` and catch this.

**Comment by sorenwacker** [comment]
Similar error appears here:
```

    maxquant_qc_protein_groups(txt_path, protein),
  File "/mnt/c/Users/soere/workspace/lrg-omics/lrg_omics/proteomics/maxquant/quality_control.py", line 237, in maxquant_qc_protein_groups
    "reporter_intensity_corrected_Protein_qc_ave": float(
  File "/home/swacker/miniconda3/envs/lrg/lib/python3.10/site-packages/pandas/core/series.py", line 206, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
```

**Comment by marioernestovaldes** [comment]
Ok, I'll work on it...

**Comment by marioernestovaldes** [comment]
fixed via https://github.com/LewisResearchGroup/lrg-omics/pull/73

**Comment by sorenwacker** [comment]
Hey @marioernestovaldes , how did you test that it works? I am still getting the same error.

```
lrg_get_maxquant_qc_data_from_path.py --path /data/ProteomicsQcTestData/EC082_G1_230406_C.raw/
>>>
Traceback (most recent call last):
  File "/home/swacker/miniconda3/envs/lrg/bin/lrg_get_maxquant_qc_data_from_path.py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/mnt/c/Users/soere/workspace/lrg-omics/scripts/lrg_get_maxquant_qc_data_from_path.py", line 13, in <module>
    df = load_maxquant_data_from(args.path)
  File "/mnt/c/Users/soere/workspace/lrg-omics/lrg_omics/proteomics/tools.py", line 35, in load_maxquant_data_from
    df = collect_maxquant_qc_data(path)
  File "/mnt/c/Users/soere/workspace/lrg-omics/lrg_omics/proteomics/maxquant/quality_control.py", line 91, in collect_maxquant_qc_data
    dfs = [maxquant_qc_csv(path, force_update=force_update) for path in paths]
  File "/mnt/c/Users/soere/workspace/lrg-omics/lrg_omics/proteomics/maxquant/quality_control.py", line 91, in <listcomp>
    dfs = [maxquant_qc_csv(path, force_update=force_update) for path in paths]
  File "/mnt/c/Users/soere/workspace/lrg-omics/lrg_omics/proteomics/maxquant/quality_control.py", line 106, in maxquant_qc_csv
    df = maxquant_qc(txt_path)
  File "/mnt/c/Users/soere/workspace/lrg-omics/lrg_omics/proteomics/maxquant/quality_control.py", line 135, in maxquant_qc
    maxquant_qc_protein_groups(txt_path, protein),
  File "/mnt/c/Users/soere/workspace/lrg-omics/lrg_omics/proteomics/maxquant/quality_control.py", line 237, in maxquant_qc_protein_groups
    "reporter_intensity_corrected_Protein_qc_ave": float(
  File "/home/swacker/miniconda3/envs/lrg/lib/python3.10/site-packages/pandas/core/series.py", line 206, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'float'>
```

Am I doing something wrong here?

**Comment by sorenwacker** [comment]
I think, the error comes when BSA is detected twice, as QC protein and as contamination. Then the average is applied to a pd.Dataframe instead of a pd.Series, and the result is a Series instead of a float.

**Comment by marioernestovaldes** [comment]
Yep, it does seem so... I'll check asap...

**Comment by marioernestovaldes** [comment]
The error happens when the qc3 df is empty. I added an if statement to detect when the qc3 df is not empty to perform the ave, std, and cv calculations, otherwise return "not detected"

fixed in https://github.com/LewisResearchGroup/lrg-omics/pull/78
